[package]
name = "grouped_by_period"
version = "0.1.0"
edition = "2021"
authors = ["Joshua Clayton <joshua.clayton@gmail.com>"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
date-calculations = "0.1"
